"use client";
import { ArrowRight, Cloud, Download, Linkedin, Mail, MapPin, Menu, Server, ShieldCheck, Workflow, X } from "lucide-react";
import { useState } from "react";
const skills=[
 {icon:Server,title:"IT Operations",text:"ITIL-led service operations, infrastructure reliability, incident, problem and change management."},
 {icon:Cloud,title:"Cloud & Modern Workplace",text:"Azure, Microsoft 365, hybrid infrastructure, SaaS and PaaS operations."},
 {icon:ShieldCheck,title:"Cybersecurity & Compliance",text:"Security controls, backup and recovery, identity management, NIS2 and audit support."},
 {icon:Workflow,title:"Transformation & Governance",text:"International programs, vendor governance, SLAs, KPIs and business-focused delivery."}
];
const experience=[
 ["2024 – PRESENT","IT Manager","Europlasma GmbH"],
 ["2022 – 2024","Digital Operations Infrastructure Engineer","XXXLutz Digital Operations"],
 ["2008 – 2021","IT Service Operations / Support Manager","NATO HQ Sarajevo"]
];
function Nav(){const [open,setOpen]=useState(false); return <><header className="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-[#07111f]/85 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6"><a href="#home" className="text-xl font-black tracking-tight">EDIN<span className="text-[#44d7ff]">.</span>ČAJO</a><nav className="hidden gap-8 text-sm text-slate-300 md:flex">{["About","Expertise","Experience","Contact"].map(x=><a className="transition hover:text-white" href={`#${x.toLowerCase()}`} key={x}>{x}</a>)}</nav><a href="#contact" className="hidden rounded-full border border-[#44d7ff]/50 px-5 py-2 text-sm font-semibold text-[#8ce8ff] md:block">Let’s connect</a><button aria-label="Open menu" className="md:hidden" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div>{open&&<nav className="grid gap-4 border-t border-white/10 px-6 py-5 md:hidden">{["About","Expertise","Experience","Contact"].map(x=><a onClick={()=>setOpen(false)} href={`#${x.toLowerCase()}`} key={x}>{x}</a>)}</nav>}</header></>}
export default function Home(){return <main><Nav/><section id="home" className="relative mx-auto grid min-h-screen max-w-7xl items-center gap-14 px-6 pb-20 pt-32 lg:grid-cols-[1.2fr_.8fr]"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#44d7ff]/20 bg-[#44d7ff]/5 px-4 py-2 text-xs font-bold tracking-[.2em] text-[#74dfff]"><span className="h-2 w-2 rounded-full bg-[#44d7ff]"/> IT LEADERSHIP · VIENNA</div><h1 className="max-w-4xl text-5xl font-black leading-[.95] tracking-[-.05em] sm:text-7xl lg:text-8xl">Transforming<br/><span className="bg-gradient-to-r from-[#44d7ff] via-[#6ea1ff] to-white bg-clip-text text-transparent">technology</span><br/>into business value.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-300">IT Manager and infrastructure leader with 26+ years of international experience across cloud, cybersecurity, service management and digital transformation.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#contact" className="flex items-center gap-2 rounded-full bg-[#2f6bff] px-7 py-4 font-bold shadow-[0_0_40px_rgba(47,107,255,.35)] transition hover:-translate-y-1">Let’s work together <ArrowRight size={18}/></a><a href="/Edin-Cajo-CV.pdf" className="flex items-center gap-2 rounded-full border border-white/15 px-7 py-4 font-bold transition hover:bg-white/5"><Download size={18}/> Download CV</a></div></div><div className="relative mx-auto w-full max-w-md"><div className="glow card relative aspect-[4/5] overflow-hidden rounded-[2rem] p-8"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_25%,rgba(68,215,255,.25),transparent_32%)]"/><div className="relative flex h-full flex-col justify-between"><div className="text-right text-xs tracking-[.25em] text-slate-400">EXECUTIVE PORTFOLIO / 2026</div><div><div className="mb-5 flex h-28 w-28 items-center justify-center rounded-3xl border border-white/15 bg-white/5 text-4xl font-black text-[#7de4ff]">EČ</div><p className="text-3xl font-black">Edin Čajo</p><p className="mt-2 text-[#71dcff]">IT Manager · Infrastructure Engineer</p></div><div className="grid grid-cols-2 gap-px overflow-hidden rounded-2xl bg-white/10"><div className="bg-[#0b1728] p-5"><b className="text-3xl">26+</b><p className="text-xs text-slate-400">YEARS EXPERIENCE</p></div><div className="bg-[#0b1728] p-5"><b className="text-3xl">17+</b><p className="text-xs text-slate-400">YEARS LEADERSHIP</p></div></div></div></div></div></section>
<section className="border-y border-white/10 bg-white/[.025]"><div className="mx-auto flex max-w-7xl flex-wrap justify-center gap-x-14 gap-y-5 px-6 py-7 text-sm font-bold tracking-[.18em] text-slate-500"><span>EUROPLASMA</span><span>XXXLUTZ</span><span>NATO</span><span>HIAS</span><span>EUFOR</span></div></section>
<section id="about" className="mx-auto max-w-7xl px-6 py-28"><div className="grid gap-14 lg:grid-cols-2"><div><p className="mb-5 text-xs font-bold tracking-[.24em] text-[#44d7ff]">ABOUT</p><h2 className="text-4xl font-black tracking-tight sm:text-5xl">Leadership built across technology, people and operations.</h2></div><div className="space-y-5 text-lg leading-8 text-slate-300"><p>I help organizations build secure, reliable and business-aligned technology environments. My career combines enterprise IT leadership with hands-on infrastructure and engineering experience.</p><p>From international organizations to European businesses, I have led teams, coordinated suppliers and delivered complex operational and transformation initiatives.</p></div></div></section>
<section id="expertise" className="mx-auto max-w-7xl px-6 pb-28"><div className="mb-12"><p className="mb-4 text-xs font-bold tracking-[.24em] text-[#44d7ff]">CORE EXPERTISE</p><h2 className="text-4xl font-black">What I bring to the table.</h2></div><div className="grid gap-5 md:grid-cols-2">{skills.map(({icon:Icon,title,text},i)=><article key={title} className="card group rounded-3xl p-8 transition hover:-translate-y-1 hover:border-[#44d7ff]/40"><div className="mb-10 flex items-start justify-between"><Icon className="text-[#52d9ff]" size={34}/><span className="text-sm text-slate-600">0{i+1}</span></div><h3 className="text-2xl font-bold">{title}</h3><p className="mt-3 leading-7 text-slate-400">{text}</p></article>)}</div></section>
<section id="experience" className="bg-[#0a1627] py-28"><div className="mx-auto max-w-7xl px-6"><p className="mb-4 text-xs font-bold tracking-[.24em] text-[#44d7ff]">SELECTED EXPERIENCE</p><h2 className="mb-14 text-4xl font-black">Career highlights.</h2><div>{experience.map((e,i)=><div key={e[1]} className="grid gap-2 border-t border-white/10 py-8 md:grid-cols-[1fr_2fr_1.5fr] md:items-center"><span className="text-sm font-bold text-[#65dcff]">{e[0]}</span><h3 className="text-xl font-bold">{e[1]}</h3><span className="text-slate-400 md:text-right">{e[2]}</span></div>)}</div></div></section>
<section id="contact" className="mx-auto max-w-7xl px-6 py-28"><div className="card overflow-hidden rounded-[2rem] p-8 sm:p-14"><div className="grid gap-10 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="mb-4 text-xs font-bold tracking-[.24em] text-[#44d7ff]">CONTACT</p><h2 className="max-w-3xl text-4xl font-black sm:text-6xl">Let’s build resilient technology that moves business forward.</h2></div><a href="mailto:edincajo@yahoo.com" className="flex w-fit items-center gap-2 rounded-full bg-white px-7 py-4 font-bold text-[#07111f]">Start a conversation <ArrowRight size={18}/></a></div><div className="mt-12 flex flex-wrap gap-6 border-t border-white/10 pt-7 text-sm text-slate-300"><a className="flex items-center gap-2" href="mailto:edincajo@yahoo.com"><Mail size={16}/> edincajo@yahoo.com</a><span className="flex items-center gap-2"><MapPin size={16}/> Vienna, Austria</span><a className="flex items-center gap-2" href="https://www.linkedin.com/in/edin%20cajo-237ab82a/"><Linkedin size={16}/> LinkedIn</a></div></div></section>
<footer className="border-t border-white/10 px-6 py-8 text-center text-sm text-slate-500">© 2026 Edin Čajo. IT leadership · Infrastructure · Transformation.</footer></main>}
